# Generated by Django 3.0.5 on 2020-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_classics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(max_length=200, null=True, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='course/%Y/%m', verbose_name='下载地址'),
        ),
    ]
