# Generated by Django 3.0.5 on 2020-05-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200513_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='机构城市'),
        ),
    ]
