# Generated by Django 3.0.5 on 2020-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_courseorg_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='info',
            field=models.CharField(max_length=200, null=True, verbose_name='老师介绍'),
        ),
    ]
